# Generated by Django 3.0.6 on 2020-05-13 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(default='未知专辑', max_length=30)),
                ('singer_name', models.CharField(default='未知歌手', max_length=20)),
                ('album_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('record_company', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.TextField(default='这是专辑简介', max_length=1200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('album_songs', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=50)),
                ('singer_name', models.CharField(max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('label_set', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('lyricist', models.CharField(blank=True, max_length=20, null=True)),
                ('composer', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('album', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
            options={
                'ordering': ('-music_name',),
            },
        ),
    ]
