# Generated by Django 3.0.6 on 2020-05-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
