# Generated by Django 3.0.6 on 2020-05-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_total_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_pic',
        ),
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y%m%d/'),
        ),
    ]
