# Generated by Django 3.0.6 on 2020-05-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200516_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='album-cover/%Y%m%d/'),
        ),
    ]
