# Generated by Django 3.0.6 on 2020-05-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200516_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, default='media/album-cover/default_cover.jpg', null=True, upload_to='album-cover/%Y%m%d/'),
        ),
    ]
