# Generated by Django 3.0.6 on 2020-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20200516_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='profile',
            field=models.TextField(default='这是专辑简介', max_length=2000),
        ),
    ]
