# Generated by Django 3.0.6 on 2020-05-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200516_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_songs',
        ),
    ]
