# Generated by Django 3.0.6 on 2020-05-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20200516_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('-name',)},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='singer_name',
            new_name='singer',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='music_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='singer_name',
            new_name='singer',
        ),
    ]
