# Generated by Django 3.0.6 on 2020-05-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20200517_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.CharField(default='未知歌手', max_length=20),
        ),
    ]
