# Generated by Django 3.0.6 on 2020-05-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20200517_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('bio', models.TextField(default='这是歌手简介', max_length=2000)),
                ('avatar', models.ImageField(blank=True, default='avatar/default.jpg', upload_to='avatar/%Y%m%d/')),
            ],
        ),
    ]
