# Generated by Django 3.0.6 on 2020-05-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20200517_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='gender',
        ),
    ]
