# Generated by Django 3.0.6 on 2020-05-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_remove_singer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='gender',
            field=models.NullBooleanField(),
        ),
    ]
