# Generated by Django 3.0.6 on 2020-05-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_singer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='label_set',
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer'),
        ),
    ]
