# Generated by Django 3.0.6 on 2020-05-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_dailyrecommendation_list_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('-time', 'user')},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_played',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='record',
            name='total_views',
        ),
    ]
