# Generated by Django 3.0.6 on 2020-05-18 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20200518_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecommendation',
            name='created',
            field=models.DateField(default=datetime.date(2020, 5, 18), unique_for_date=True),
        ),
    ]
