# Generated by Django 3.0.6 on 2020-05-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20200517_1330'),
        ('music', '0021_auto_20200518_1040'),
    ]

    operations = [
    ]
