# Generated by Django 3.0.6 on 2020-05-19 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_merge_20200519_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='music',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='tags',
        ),
        migrations.AddField(
            model_name='album',
            name='gender',
            field=models.IntegerField(choices=[(1, '女'), (2, '男'), (3, '组合')], default=1),
        ),
        migrations.AlterField(
            model_name='dailyrecommendation',
            name='created',
            field=models.DateField(default=datetime.date(2020, 5, 19), unique_for_date=True),
        ),
    ]
