# Generated by Django 3.0.6 on 2020-05-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20200519_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='gender',
        ),
        migrations.AlterField(
            model_name='singer',
            name='gender',
            field=models.IntegerField(choices=[(1, '女'), (2, '男'), (3, '组合')], default=1),
        ),
    ]
