# Generated by Django 3.0.6 on 2020-05-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20200519_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='未知专辑', max_length=30),
        ),
    ]
