# Generated by Django 3.0.6 on 2020-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_musictag_singertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='tag',
            field=models.ManyToManyField(related_name='list_tags', to='music.MusicTag'),
        ),
    ]
