# Generated by Django 3.0.6 on 2020-05-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_singer_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='singer_tags', to='music.SingerTag'),
        ),
    ]
