# Generated by Django 3.0.6 on 2020-05-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_auto_20200519_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='music_tags', to='music.MusicTag'),
        ),
    ]
