# Generated by Django 3.0.6 on 2020-05-20 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_music_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecommendation',
            name='created',
            field=models.DateField(default=datetime.date(2020, 5, 20), unique_for_date=True),
        ),
    ]
