# Generated by Django 3.0.6 on 2020-05-21 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0031_auto_20200520_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecommendation',
            name='created',
            field=models.DateField(default=datetime.date(2020, 5, 21), unique_for_date=True),
        ),
    ]
