# Generated by Django 3.0.6 on 2020-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_auto_20200521_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecommendation',
            name='created',
            field=models.DateField(unique_for_date=True),
        ),
    ]
