# Generated by Django 3.0.6 on 2020-05-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_auto_20200522_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='music_tags', to='music.MusicTag'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='singer_tags', to='music.SingerTag'),
        ),
    ]
