# Generated by Django 3.0.6 on 2020-05-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_auto_20200523_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
