# Generated by Django 3.0.6 on 2020-05-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0031_auto_20200520_1229'),
        ('userprofile', '0003_likesanddislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likesanddislikes',
            name='singer_disliked',
        ),
        migrations.AddField(
            model_name='likesanddislikes',
            name='singer_disliked',
            field=models.ManyToManyField(blank=True, null=True, related_name='singer_disliked', to='music.Singer'),
        ),
        migrations.RemoveField(
            model_name='likesanddislikes',
            name='singer_liked',
        ),
        migrations.AddField(
            model_name='likesanddislikes',
            name='singer_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='singer_liked', to='music.Singer'),
        ),
        migrations.RemoveField(
            model_name='likesanddislikes',
            name='song_disliked',
        ),
        migrations.AddField(
            model_name='likesanddislikes',
            name='song_disliked',
            field=models.ManyToManyField(blank=True, null=True, related_name='song_disliked', to='music.Music'),
        ),
        migrations.RemoveField(
            model_name='likesanddislikes',
            name='tag_disliked',
        ),
        migrations.AddField(
            model_name='likesanddislikes',
            name='tag_disliked',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag_disliked', to='music.MusicTag'),
        ),
        migrations.RemoveField(
            model_name='likesanddislikes',
            name='tag_liked',
        ),
        migrations.AddField(
            model_name='likesanddislikes',
            name='tag_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag_liked', to='music.MusicTag'),
        ),
    ]
